name: DockerHub README

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yaml

jobs:
  push-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push README to DockerHub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: hteppl/remnawave-cloudflare-nodes
          provider: dockerhub
          short_description: "Automatically manage Cloudflare DNS records based on Remnawave (https://docs.rw) node health status."
          readme_file: "README.md"
